updated court to location and inculuded new logic
hmcts/pip-data-management pull request #109
Opened 2022-05-12 09:57 UTC by kurt-uk

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PUB-1264

### Change description ###
Updated "court" references to "location" (only where appropriate for the scope of this story)
updated location table and location_reference table to hold a LocationType value which determines venue, region, owning hearing location or national. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[x] Yes
[ ] No
```

2022-05-12 18:08 UTC, ChrisS1512 requested changes
I've noticed flyway is failing. I'm wondering if it's best just to remove it as it's no longer needed.

2022-05-13 09:54 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/data/management/models/location/Location.java
> +     * Adds a new CourtReference to the reference table.
whoops, done

2022-05-13 12:49 UTC, ChrisS1512 approved these changes

2022-05-13 12:56 UTC, furnivall approved these changes
LGTM

2022-05-27 10:18 UTC, merged