Pub 1312 Sensitivity Updates
hmcts/pip-data-management pull request #117
Opened 2022-05-26 15:56 UTC by ChrisS1512

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1312

### Change description ###

Updates to handle Sensitivity when returning requests. Data Management now makes a call to Account Management to determine whether the passed in user ID has permission to see the publication.

The verified flag on the endpoint has been replaced with this.

Also x-admin has now been added to the get flat file / payload endpoints, so that pub services is able to pull back to the file.

**Does this PR introduce a breaking change?** (check one with "x")

```
[x] Yes
[] No
```

2022-05-30 09:10 UTC, kurt-uk requested changes

2022-05-30 09:10 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java
> +        throw new NotFoundException(String.format("No artefact found with the ID: %s", artefactId));
```suggestion
        throw new ArtefactNotFoundException(String.format("No artefact found with the ID: %s", artefactId));
```

2022-05-30 09:10 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java
> +        throw new NotFoundException(String.format("No artefact found with the ID: %s", artefactId));
```suggestion
        throw new ArtefactNotFoundException(String.format("No artefact found with the ID: %s", artefactId));
```

2022-06-07 16:18 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/data/management/service/AccountManagementService.java
> +            return webClient.get().uri(new URI(String.format(
Removed the use of URI

2022-06-07 16:19 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/data/management/service/AccountManagementService.java
> +            return webClient.get().uri(new URI(String.format(
Removed the use of URI

2022-06-07 16:19 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/data/management/service/AccountManagementService.java
> +            log.error(String.format("Request failed with error message: %s", ex.getMessage()));
Now updated

2022-06-07 16:19 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/data/management/service/AccountManagementService.java
> +            log.error(String.format("Request failed with error message: %s", ex.getMessage()));
Now updated

2022-06-07 16:19 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java
> +        throw new NotFoundException(String.format("No artefact found with the ID: %s", artefactId));
Updated

2022-06-07 16:29 UTC, joshblackmoor approved these changes

2022-06-08 08:28 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationController.java
> +
Yes, you are right. Both options will work. That's fine with me :)

2022-06-08 08:37 UTC, kurt-uk approved these changes

2022-06-08 09:15 UTC, junaidiqbalmoj approved these changes
LGTM...

2022-06-08 17:34 UTC, merged