PUB-1597 Spring Updates
hmcts/pip-data-management pull request #175
Opened 2022-10-26 14:04 UTC by joshblackmoor

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1597

### Change description ###

- Updated Spring boot to 2.7.4
- Removed Spring fox and replaced it with Spring Doc
- Updated JUnit

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-10-28 13:14 UTC, KianKwa approved these changes

2022-10-31 09:19 UTC, ChrisS1512 requested changes
Looks good! Just some conflicts on this one that needs fixing

2022-10-31 10:55 UTC, joshblackmoor commented
> Looks good! Just some conflicts on this one that needs fixing

Sorted conflicts

2022-10-31 11:07 UTC, ChrisS1512 approved these changes

2022-11-01 12:48 UTC, merged