PUB-1686 Refactor publication service
hmcts/pip-data-management pull request #258
Opened 2023-01-06 16:10 UTC by junaidiqbalmoj

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1686

### Change description ###

Refactor PublicationService class into sub classes. Seperate the tests as well.

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2023-01-10 16:54 UTC, joshblackmoor reviewed
Looks really good 👍

2023-01-10 16:54 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactService.java
> +    private static final char DELIMITER = ',';
Can't see where this is used :)

2023-01-10 17:39 UTC, joshblackmoor approved these changes

2023-01-12 11:05 UTC, ChrisS1512 requested changes

2023-01-12 11:58 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/data/management/helpers/ArtefactHelper.java
> +    public static String getUuidFromUrl(String payloadUrl) {
added.

2023-01-12 12:05 UTC, ChrisS1512 approved these changes

2023-01-13 11:59 UTC, merged