Pub 1904
hmcts/pip-data-management pull request #435
Opened 2023-08-16 10:20 UTC by NatashaAlker

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1904

### Change description ###

List clean up for IAC list to remove unused elements of JSON mock file

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-08-17 08:20 UTC, ChrisS1512 requested changes
Looks good! There's also a couple of files in the functionalTest resources test folder for IAC Would you be able to clean those up too?

2023-08-17 08:32 UTC, KianKwa commented on src/main/resources/schemas/iac_daily_list.json
> -                          "sessionChannel": {
Changes look good but this field will need to be removed from the confluence page too. Also the example JSON on that confluence page will need to have those elements removed :) 
https://tools.hmcts.net/confluence/display/PUBH/Immigration+and+Asylum+Daily+Cause+List

2023-08-22 11:01 UTC, KianKwa approved these changes

2023-08-25 10:07 UTC, ChrisS1512 approved these changes

2023-08-25 10:08 UTC, merged