Pub 2186 iac daily cause list updates
hmcts/pip-data-management pull request #565
Opened 2024-03-06 12:50 UTC by MindGames2015

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

https://tools.hmcts.net/jira/browse/PUB-2186

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-03-22 09:18 UTC, ChrisS1512 requested changes
Looks good.

The test files in the functionalTest folder also need updating, then happy to approve

2024-03-22 12:08 UTC, MindGames2015 commented
> Looks good.
> 
> The test files in the functionalTest folder also need updating, then happy to approve

2024-03-25 09:11 UTC, ChrisS1512 approved these changes

2024-04-05 10:22 UTC, ChrisS1512 approved these changes

2024-04-19 12:33 UTC, merged