PUB-2190: Added 'caseType' field to Civil Daily Cause list
hmcts/pip-data-management pull request #575
Opened 2024-03-21 09:29 UTC by alexbottenberg

https://tools.hmcts.net/jira/browse/PUB-2190

Added 'caseType' field to Civil Daily Cause list and mocks

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-03-21 14:35 UTC, MindGames2015 approved these changes

2024-03-21 14:44 UTC, KianKwa requested changes
We will also need to update the test data in the functional test folder

2024-03-21 16:24 UTC, KianKwa commented on src/functionalTest/resources/data/family-daily-cause-list/familyDailyCauseList.json
> +                            "caseType": "Case type",
Hey Alex, the test file needs updated for this should be in civil-and-family-daily-cause-list

2024-03-22 11:27 UTC, KianKwa approved these changes

2024-04-02 09:25 UTC, merged